version: '3.3'
services:
  profile-service:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    links: 
      - mongo
    environment:
      - DATABASE_URI=mongodb://mongo/finance-tracker

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
      
volumes:
  mongodb: